name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pull docker image
      run: docker pull ghcr.io/7dog123/wkf/run-on-arch-7dog123-wkf-ci-armv7-bullseye:latest
